### ISSUE TITLE
retry for ConnectionError

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/signingscript#66]
We had some signing failures during a release today that were rooted in signing server restarts. The tracebacks looked as follows:

```
2018-08-23 17:00:35,158 - signingscript.utils - INFO - 2018-08-23 17:00:35,158 - Starting new HTTPS connection (1): mac-v2-signing13.srv.releng.mdc2.mozilla.com:9120
2018-08-23 17:00:44,058 - signingscript.utils - INFO - Traceback (most recent call last):
2018-08-23 17:00:44,059 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/signtool/signing/client.py", line 86, in remote_signfile
2018-08-23 17:00:44,059 - signingscript.utils - INFO -     r.raise_for_status()
2018-08-23 17:00:44,059 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
2018-08-23 17:00:44,059 - signingscript.utils - INFO -     raise HTTPError(http_error_msg, response=self)
2018-08-23 17:00:44,059 - signingscript.utils - INFO - requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mac-v2-signing13.srv.releng.mdc2.mozilla.com:9120/sign/dmg/457867ecdd321c167f0d61fca1d07b2c9cc43cf4
2018-08-23 17:00:44,059 - signingscript.utils - INFO - 
2018-08-23 17:00:44,059 - signingscript.utils - INFO - During handling of the above exception, another exception occurred:
2018-08-23 17:00:44,059 - signingscript.utils - INFO - 
2018-08-23 17:00:44,059 - signingscript.utils - INFO - Traceback (most recent call last):
2018-08-23 17:00:44,059 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
2018-08-23 17:00:44,059 - signingscript.utils - INFO -     chunked=chunked)
2018-08-23 17:00:44,059 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
2018-08-23 17:00:44,059 - signingscript.utils - INFO -     conn.request(method, url, **httplib_request_kw)
2018-08-23 17:00:44,059 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1239, in request
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     self._send_request(method, url, body, headers, encode_chunked)
2018-08-23 17:00:44,060 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1285, in _send_request
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     self.endheaders(body, encode_chunked=encode_chunked)
2018-08-23 17:00:44,060 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1234, in endheaders
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     self._send_output(message_body, encode_chunked=encode_chunked)
2018-08-23 17:00:44,060 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1065, in _send_output
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     self.send(chunk)
2018-08-23 17:00:44,060 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 986, in send
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     self.sock.sendall(data)
2018-08-23 17:00:44,060 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/ssl.py", line 972, in sendall
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     v = self.send(byte_view[count:])
2018-08-23 17:00:44,060 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/ssl.py", line 941, in send
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     return self._sslobj.write(data)
2018-08-23 17:00:44,060 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/ssl.py", line 642, in write
2018-08-23 17:00:44,060 - signingscript.utils - INFO -     return self._sslobj.write(data)
2018-08-23 17:00:44,060 - signingscript.utils - INFO - BrokenPipeError: [Errno 32] Broken pipe
2018-08-23 17:00:44,060 - signingscript.utils - INFO - 
2018-08-23 17:00:44,060 - signingscript.utils - INFO - During handling of the above exception, another exception occurred:
2018-08-23 17:00:44,061 - signingscript.utils - INFO - 
2018-08-23 17:00:44,061 - signingscript.utils - INFO - Traceback (most recent call last):
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
2018-08-23 17:00:44,061 - signingscript.utils - INFO -     timeout=timeout
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
2018-08-23 17:00:44,061 - signingscript.utils - INFO -     _stacktrace=sys.exc_info()[2])
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
2018-08-23 17:00:44,061 - signingscript.utils - INFO -     raise six.reraise(type(error), error, _stacktrace)
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
2018-08-23 17:00:44,061 - signingscript.utils - INFO -     raise value.with_traceback(tb)
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
2018-08-23 17:00:44,061 - signingscript.utils - INFO -     chunked=chunked)
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
2018-08-23 17:00:44,061 - signingscript.utils - INFO -     conn.request(method, url, **httplib_request_kw)
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1239, in request
2018-08-23 17:00:44,061 - signingscript.utils - INFO -     self._send_request(method, url, body, headers, encode_chunked)
2018-08-23 17:00:44,061 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1285, in _send_request
2018-08-23 17:00:44,062 - signingscript.utils - INFO -     self.endheaders(body, encode_chunked=encode_chunked)
2018-08-23 17:00:44,062 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1234, in endheaders
2018-08-23 17:00:44,062 - signingscript.utils - INFO -     self._send_output(message_body, encode_chunked=encode_chunked)
2018-08-23 17:00:44,062 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 1065, in _send_output
2018-08-23 17:00:44,062 - signingscript.utils - INFO -     self.send(chunk)
2018-08-23 17:00:44,062 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/http/client.py", line 986, in send
2018-08-23 17:00:44,062 - signingscript.utils - INFO -     self.sock.sendall(data)
2018-08-23 17:00:44,062 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/ssl.py", line 972, in sendall
2018-08-23 17:00:44,062 - signingscript.utils - INFO -     v = self.send(byte_view[count:])
2018-08-23 17:00:44,062 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/ssl.py", line 941, in send
2018-08-23 17:00:44,062 - signingscript.utils - INFO -     return self._sslobj.write(data)
2018-08-23 17:00:44,062 - signingscript.utils - INFO -   File "/tools/python36/lib/python3.6/ssl.py", line 642, in write
2018-08-23 17:00:44,062 - signingscript.utils - INFO -     return self._sslobj.write(data)
2018-08-23 17:00:44,062 - signingscript.utils - INFO - urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
2018-08-23 17:00:44,062 - signingscript.utils - INFO - 
2018-08-23 17:00:44,062 - signingscript.utils - INFO - During handling of the above exception, another exception occurred:
2018-08-23 17:00:44,062 - signingscript.utils - INFO - 
2018-08-23 17:00:44,062 - signingscript.utils - INFO - Traceback (most recent call last):
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/bin/signtool", line 11, in <module>
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     load_entry_point('signtool==3.2.0', 'console_scripts', 'signtool')()
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/signtool/signtool.py", line 278, in main
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     sign(options, args)
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/signtool/signtool.py", line 265, in sign
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     if not remote_signfile(options, urls, f, fmt, token, dest):
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/signtool/signing/client.py", line 136, in remote_signfile
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     r = uploadfile(url, filename, fmt, token, nonce, options.cert)
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/signtool/signing/client.py", line 177, in uploadfile
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     return method("%s/sign/%s" % (baseurl, format_), files=files, data=payload, verify=cert)
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/requests/api.py", line 112, in post
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     return request('post', url, data=data, json=json, **kwargs)
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/requests/api.py", line 58, in request
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     return session.request(method=method, url=url, **kwargs)
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     resp = self.send(prep, **send_kwargs)
2018-08-23 17:00:44,063 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
2018-08-23 17:00:44,063 - signingscript.utils - INFO -     r = adapter.send(request, **kwargs)
2018-08-23 17:00:44,064 - signingscript.utils - INFO -   File "/builds/scriptworker/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
2018-08-23 17:00:44,065 - signingscript.utils - INFO -     raise ConnectionError(err, request=request)
2018-08-23 17:00:44,065 - signingscript.utils - INFO - requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
2018-08-23 17:00:44,093 - signingscript.utils - INFO - exitcode 1
2018-08-23 17:00:44,094 - scriptworker.client - ERROR - Failed to run async_main
Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/client.py", line 203, in _handle_asyncio_loop
    await async_main(context)
  File "/builds/scriptworker/lib/python3.6/site-packages/signingscript/script.py", line 54, in async_main
    context, os.path.join(work_dir, path), path_dict['formats']
  File "/builds/scriptworker/lib/python3.6/site-packages/signingscript/task.py", line 169, in sign
    output = await signing_func(context, output, fmt)
  File "/builds/scriptworker/lib/python3.6/site-packages/signingscript/sign.py", line 198, in sign_macapp
    await sign_file(context, from_, fmt)
  File "/builds/scriptworker/lib/python3.6/site-packages/signingscript/sign.py", line 137, in sign_file
    await utils.execute_subprocess(cmd)
  File "/builds/scriptworker/lib/python3.6/site-packages/signingscript/utils.py", line 159, in execute_subprocess
    raise FailedSubprocess('Command `{}` failed'.format(' '.join(command)))
```

(full log is at https://taskcluster-artifacts.net/eOtkYFf9QYyZf7dOeI8kJA/0/public/logs/live_backing.log)

It seems like these should be retried for.

**Comment by escapewindow** [comment]
It looks like this is breaking in the signtool upload.
We could put a retry around [this line](https://github.com/mozilla-releng/signingscript/blob/master/signingscript/sign.py#L137), but I think it might be wiser to wrap [this line](https://github.com/mozilla-releng/signtool/blob/master/signtool/signing/client.py#L177) in a retry.
